# Generated by Django 4.2.7 on 2025-10-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('crisis', 'Crisis Detected'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('crisis', 'Crisis - Immediate Attention Needed')], default='low', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('depression_score', models.IntegerField(default=0)),
                ('anxiety_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('scale', 'Rating Scale (0-3)'), ('multiple', 'Multiple Choice'), ('text', 'Text Response'), ('yesno', 'Yes/No')], max_length=20)),
                ('category', models.CharField(choices=[('depression', 'Depression'), ('anxiety', 'Anxiety'), ('sleep', 'Sleep'), ('appetite', 'Appetite'), ('energy', 'Energy'), ('mood', 'Mood'), ('social', 'Social Functioning'), ('general', 'General Health')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('trigger_value', models.CharField(blank=True, max_length=50)),
                ('depends_on_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('risk_factors', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
